version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.1
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.cache/composer:/root/.composer/cache # use a local cache.
